version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80"
    volumes:
      - ./src:/app

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - "./infra/prometheus.yml:/etc/prometheus/prometheus.yml"

  exporterFPM:
    image: hipages/php-fpm_exporter:latest
    ports:
      - "9253:9253"
    depends_on:
      - app
    environment:
      PHP_FPM_SCRAPE_URI: "tcp://app:9000/status"
      PHP_FPM_LOG_LEVEL: "debug"

  exporterNginx:
    image: nginx/nginx-prometheus-exporter:0.3.0
    ports:
      - "9113:9113"
    depends_on:
      - app
    command: ["-nginx.scrape-uri", "http://app:80/stub_status"]
  

  grafana:
    image: grafana/grafana
    ports:
      - "3000"
    depends_on:
      - app
    environment:
      GF_SECURITY_ADMIN_PASSWORD: password